version: 2
updates:

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      # Check for bundler updates using the package manifest (Gemfile) every weekday
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
