name: Integration Tests
concurrency:
  group: integ-tests-${{ github.repository }}-${{ github.ref }}

on:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-20.04

    services:
      chrome:
        image: selenium/standalone-chrome:latest

    steps:
      - name: Set up Python...
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.9.7'
          architecture: 'x64'

      - name: Install Selenium Python Bindings...
        run: pip install -U selenium    
        
      - name: Download Selenium tests...
        run: git clone https://github.com/slateci/slateci-unit-tests.git

      - name: Run Selenium tests...
        run: python slateci-unit-tests/main.py
      
      # Return result to Slack if tests failed
      - name: Notify Slack Fail
        if: failure()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel_id: CLRGHCWG3
          status: FAILED
          color: danger
