name: Integration Tests
concurrency:
  group: integ-tests-${{ github.repository }}-${{ github.ref }}

on:
  push:
    branches:
      - 214-integration-tests-consistently-fail
#  workflow_run:
#    workflows:
#      - pages-build-deployment
#    types:
#      - completed

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-22.04
    container: joyzoursky/python-chromedriver:3.9-selenium

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .
          ref: 14-integration-tests-seleniumcommonexceptionstimeoutexception
          repository: slateci/slateci-unit-tests

      - name: Run Selenium tests
        run: python main.py

      - name: Notify Slack of Failure
        if: failure()
        uses: slateci/github-actions/.github/actions/slack-notify-failure@v13
        with:
          slack_bot_token: '${{ secrets.SLACK_BOT_TOKEN }}'
